### ISSUE TITLE
Selects dont have enough right padding to protect their down-chevrons from text

### ISSUE THREAD

**Issue by Daemios** [dynamicsuite/dspkg-aui#18]

**Comment by commgdog** [comment]
Please provide a screenshot example

**Comment by Daemios** [comment]
![image](https://user-images.githubusercontent.com/7331701/96416046-513a0e00-11a4-11eb-898f-75e8e7fb7ef8.png)

**Comment by commgdog** [comment]
Would the proposed solution just pad and truncate the text value, or disable the chevron entirely? There is currently a similar flag on them for disabling the feedback icon, useful for situations when the select is shorter than content length

**Comment by Daemios** [comment]
Fixed and pushed
